# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 签到薅羊毛

on:
  schedule:
    # 此处是UTC时间，对应北京时间早八点
    - cron : '00 00 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run weather Report
      run: |
        python daily_sign.py
      env:
        JD_COOKIE: ${{3AB9D23F7A4B3C9B=BWPQSPOVBIDNZVGC3UISQJ2YGIN65M72UT2TSQCFQZQFGMJ2RF2NT5BFGMFENVRIKST6MZUJNYOQXQEQZGJAMYYLMQ; shshshfpa=17e72076-9860-bc7f-ce01-11b8756fa3a1-1732014851; shshshfpx=17e72076-9860-bc7f-ce01-11b8756fa3a1-1732014851; ipLoc-djd=17-1381-50712-62966; autoOpenApp_downCloseDate_auto=1732015183366_1800000; unpl=JF8EALBnNSttD0pQV0hRGRoSG19WW19cTURUPGcAVl9bTwYHEwIcFBB7XlVdWBRLFx9vbxRUVVNIXQ4aAisSEHteVV1fAUwXB2tkNWRdWUpXBhMHGhMYe15Ublw4SxEAZ2MBVl9YSlUAEgUZERhNW11ZXjhKJwNnYDVUXFhIVgUSBRwWFUhYUG5tCXsWM25XRDpdW05QBRkBEl8QTV5cWlkKSRcCbmIMU19bQ1IDEgUYIhF7Xg; __jdv=181111935%7Clianmeng__10__api.shop.xuelg.com%7Ct_2023861552_%7Cjingfen%7Cf05cbb393a3343e7bfb143325c391671%7C1732015683278; autoOpenApp_downCloseDate_jd_independent_coupon_openapp=1732015830366_1; __jda=76161171.1729553310048632977862.1729553310.1732015683.1732970052.8; __jdc=76161171; 3AB9D23F7A4B3CSS=jdd03BWPQSPOVBIDNZVGC3UISQJ2YGIN65M72UT2TSQCFQZQFGMJ2RF2NT5BFGMFENVRIKST6MZUJNYOQXQEQZGJAMYYLMQAAAAMTPUIHUSYAAAAACA3BOXZ33L6EPYX; _gia_d=1; PCSYCityID=CN_420000_420100_0; shshshfpb=BApXSlTsYfvZAEY5maidSy3zIeM_OqRJ7BnBAT35p9xJ1MrpIIYG2; __jdb=76161171.2.1729553310048632977862|8.1732970052}}
